---
title: "WalshTemperatureProfileAndMixing"
author: "Elizabeth Davenport"
date: '2023-11-20'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial stuff, including loading packages and importing data

##loading packages
```{r,message=F,warning=F}
library(here)
library(rstatix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(lubridate)
library(scales)
library(ggpubr)
library(reshape2)
library(RColorBrewer)
```
## loading files

```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/WalshTemperatureProfileAndMixing.Rmd")

# Load Files
a <- readr::read_csv(here("data/WalshMixingDepthCV.csv"))
c <- readr::read_csv(here("data/Walsh_Basin_Thermal_Profile_2021.csv"))
```

##Walsh Thermal Profile
```{r,message=F,warning=F}
z <- strptime(c$Date, format = "%m/%d/%y  %H:%M")
##strptime(z, format = "%m/%d/%y  %H:%M")
l <- as.POSIXct(z,format="%m/%d/%y %H:%M",tz=Sys.timezone())

W.1 <- c$B1
W.2 <- c$B2
W.3 <- c$B3
W.4 <- c$B4
W.5 <- c$B5
W.SWI <- c$SWI
W.surf <- c$Surface

df.WB <- data.frame(check.names = FALSE, time = l,
                    "1m" = W.1,
                    "2m" = W.2,
                    "3m" = W.3,
                    "4m" = W.4,
                    "5m" = W.5,
                      "Surface" = W.surf)
df.WB <- melt(df.WB ,  id.vars = 'time', variable.name = 'series')

colsB<- brewer.pal(9,"Blues")
colsB2 <- c("Surface"= "#C6DBEF", "1m"= "#9ECAE1", "2m"="#6BAED6", "3m"="#4292C6","4m"= "#2171B5","5m"= "#08519C","6m"= "#08306B")
colsB <- c("0"= "#C6DBEF", "1"= "#9ECAE1", "2"="#6BAED6", "3"="#4292C6","4"= "#2171B5","5"= "#08519C","6"= "#08306B")


WB.combined = ggplot() + geom_line(df.WB,mapping=aes(x=time,y=value, colour = factor(series)), size=1) +
  scale_colour_manual(values = colsB2)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-06-14")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-06-28")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-07-12")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-07-26")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-08-09")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-08-23")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-09-07")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-09-20")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-10-04")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-10-18")), linetype="dotted", 
             color = "black", size=1)+
  
  geom_vline(xintercept = as.POSIXct(as.Date("2021-11-01")), linetype="dotted", 
             color = "black", size=1)+
  
  geom_vline(xintercept = as.POSIXct(as.Date("2021-11-12")), linetype="dotted", 
             color = "black", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-09-22")), linetype="dotted", 
         color = "#009E73", size=1)+
  geom_vline(xintercept = as.POSIXct(as.Date("2021-10-22")), linetype="dotted", 
             color = "#D55E00", size=1)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black")) +
  scale_y_continuous(limits = c(5, 30), breaks = seq(5, 30, 5))+
  labs(x = "",
       y = (expression(bold("Temperature " ( degree*C))))) +
  ggtitle("Thermal Profile") +
  theme(plot.title = element_text(face = "bold",size = 14)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=12,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 12),
        legend.text=element_text(size=10,face="bold"),
        legend.position = "bottom") + 
  scale_x_datetime(breaks = date_breaks("21 days"), labels = date_format("%m/%d/%y")) +
  labs(colour = "Depth")
WB.combined
```

#### Boxplot of coefficient of variation
```{r,message=F,warning=F}
Walsh <- na.omit(a)

r <- as.factor(Walsh$Round)
CV<-Walsh$CV
mix<-as.factor(Walsh$`Mixing Depth`)

##my_comparisons <- list( c("9", "10"),c("9", "11"),c("9", "12"))

CVwalsh <- ggplot(data=Walsh,aes(x=r,y=CV, fill=mix)) +
  geom_boxplot()+
  scale_y_continuous(limits = c(0,3.5), breaks = seq(0,3.5,.5))+
  geom_vline(xintercept = 10.5, color="#D55E00", size=1)+
  geom_vline(xintercept = 8.5, color="#009E73", size=1)+
  scale_fill_manual(values = colsB)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("Patchiness over Time") +
  labs(x = ("Sampling Round"), y=("Coefficient of Variation"),fill=("Depth"))+
  theme(plot.title = element_text(face = "bold",size = 14)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=12,face="bold")) +
  theme(legend.position = "bottom")

CVwalsh
```

### Mixing Depth
```{r,message=F,warning=F}
## creating a data frame
df1<- data.frame(r, mix, CV)

#### setting comparisons for wilcox test
my_comparisons <- list(c("1", "5"))

## Wilcoxon Test
wtest<-compare_means(CV ~ mix,  data = df1, method="wilcox.test", paired = FALSE)


CVwalshMix <- ggplot(data=df1,aes(x=mix,y=CV, fill=mix)) +
  geom_boxplot()+
  scale_y_continuous(limits = c(0,3.5), breaks = seq(0,3.5,.5))+
  scale_x_discrete(breaks=seq(0,5,1))+
  scale_fill_manual(values = colsB)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("Mixing Depth and Patchiness") +
  labs(x = ("Mixing Depth (m)"), y=("Patchiness"), fill=("Depth"))+
  theme(plot.title = element_text(face = "bold",size = 14)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=12,face="bold")) +
  theme(legend.position = "bottom")+
  guides(fill = guide_legend(override.aes = list(size = 0.15)))+
  theme(legend.title = element_text(face = "bold"))+
  stat_compare_means(method="wilcox.test", paired=FALSE, comparisons = my_comparisons, hide.ns=FALSE) # Add pairwise comparisons p-value


CVwalshMix
```

###Combined Plot
```{r,message=F,warning=F}

leg <- get_legend(CVwalshMix)
CVwalshMix <- CVwalshMix + theme(legend.position = "none")
combined = ggarrange(WB.combined, CVwalsh, ggarrange(CVwalshMix, leg, ncol=2),
                     nrow = 3, labels = c("A.","B.","C."),
                     heights = c(1.5,1,1),
                     common.legend = FALSE,
                     legend="none")


combined=annotate_figure(combined,top = text_grob("Walsh Lake", color = "black", face = "bold", size = 16))

combined

#### saving combined plot
ggsave(here("figures", "Walsh_Combined_TemperatureProfile_Patchiness_Mixing_v4.jpg"), combined, width = 10, height = 12, dpi = 300)
```
