---
title: "CedarNearshoreOffshoreTemperatureDifference"
author: "Elizabeth Davenport"
date: '2023-11-22'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Initial stuff, including loading packages and importing data

##loading packages
```{r,message=F,warning=F}
library(here)
library(rstatix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(lubridate)
library(scales)
library(ggpubr)
library(reshape2)
library(RColorBrewer)
require(ggplot2)
require(reshape2)
```
## loading files

```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/CedarNearshoreOffshoreTemperatureDifference.Rmd")

# Load Files
a <- readr::read_csv(here("data/Cedar_Basin_Nearshore.csv"))
```

```{r,message=F,warning=F}
z <- strptime(a$Date, format = "%m/%d/%y  %H:%M")
l <- as.POSIXct(z,format="%m/%d/%y %H:%M",tz=Sys.timezone())

C.TDiff.1 <- a$Diff.1
C.TDiff.2 <- a$Diff.2
C.TDiff.3 <- a$Diff.3

df.CTDiff1 <- data.frame(check.names = FALSE, time = l,
                         "1m" = C.TDiff.1)

df.CTDiff1 <- melt(df.CTDiff1 ,  id.vars = 'time', variable.name = 'series')

CTdiff1 = ggplot(df.CTDiff1, aes(time,value)) + geom_line(aes(colour = series)) +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black")) +
  scale_y_continuous(limits = c(-1.5, 1.5), breaks = seq(-1.5, 1.5, 0.5))+
  labs(x = "",
       y = (expression(bold("Temperature Difference " ( degree*C))))) +
  ggtitle("Thermal Difference at 1m in Cedar") +
  theme(plot.title = element_text(face = "bold",size = 14)) +
  theme(axis.text=element_text(size=11, face = "bold"), 
        axis.title=element_text(size=14,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 14),
        legend.text=element_text(size=11,face="bold")) + 
  scale_x_datetime(breaks = date_breaks("14 days"), labels = date_format("%m/%d/%y")) +
  ##labs(colour = "Depth") +
  theme(legend.position = "none") +
  geom_hline(yintercept=0)


##########################################################################################
##   2m

df.CTDiff2 <- data.frame(check.names = FALSE, time = l,
                         "2m" = C.TDiff.2)

df.CTDiff2 <- melt(df.CTDiff2 ,  id.vars = 'time', variable.name = 'series')

CTdiff2 = ggplot(df.CTDiff2, aes(time,value)) + geom_line(aes(colour = series)) +
  scale_color_manual(values = "dodgerblue") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black")) +
  scale_y_continuous(limits = c(-1.5, 1.5), breaks = seq(-1.5, 1.5, 0.5))+
  labs(x = "",
       y = (expression(bold("Temperature Difference " ( degree*C))))) +
  ggtitle("Thermal Difference at 2m in Cedar") +
  theme(plot.title = element_text(face = "bold",size = 14)) +
  theme(axis.text=element_text(size=11, face = "bold"), 
        axis.title=element_text(size=14,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 14),
        legend.text=element_text(size=11,face="bold")) + 
  scale_x_datetime(breaks = date_breaks("14 days"), labels = date_format("%m/%d/%y")) +
  theme(legend.position = "none") +
  geom_hline(yintercept=0)


###########################################################################################
## 3m

df.CTDiff3 <- data.frame(check.names = FALSE, time = l,
                         "3m" = C.TDiff.3)

df.CTDiff3 <- melt(df.CTDiff3,  id.vars = 'time', variable.name = 'series')

CTdiff3 = ggplot(df.CTDiff3, aes(time,value)) + geom_line(aes(colour = series)) +
  scale_color_manual(values = "forestgreen") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black")) +
  scale_y_continuous(limits = c(-1.5, 1.5), breaks = seq(-1.5, 1.5, 0.5))+
  labs(x = "",
       y = (expression(bold("Temperature Difference " ( degree*C))))) +
  ggtitle("Thermal Difference at 3m in Cedar") +
  theme(plot.title = element_text(face = "bold",size = 14)) +
  theme(axis.text=element_text(size=11, face = "bold"), 
        axis.title=element_text(size=14,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 14),
        legend.text=element_text(size=11,face="bold")) + 
  scale_x_datetime(breaks = date_breaks("14 days"), labels = date_format("%m/%d/%y")) +
  theme(legend.position = "none") +
  geom_hline(yintercept=0)


###########################################################################################


TDiff_C = ggarrange(CTdiff1, CTdiff2, CTdiff3, nrow = 2, ncol = 2,
                    common.legend = FALSE)

#### saving combined plot
ggsave(here("figures", "CedarNearshoreOffshoreTemperatureDifference.jpg"), TDiff_C, width = 18, height = 11, dpi = 300)
```