---
title: "SporePatchinessNearshoreOffshore"
author: "Elizabeth Davenport"
date: '2023-11-22'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial stuff, including loading packages and importing data

##loading packages
```{r,message=F,warning=F}
library(here)
library(rstatix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(ggpubr)
library(lubridate)
library(scales)
```
## loading files

```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/SporePatchinessNearshoreOffshore.Rmd")

# Load Files
a <- readr::read_csv(here("data/CV_Walsh_LocationsDates.csv"))
b <- readr::read_csv(here("data/CV_LilAp_LocationsDates.csv"))
c <- readr::read_csv(here("data/CV_Cedar_LocationsDates.csv"))

```

```{r,message=F,warning=F}
a <- na.omit(a)
r <- as.factor(a$Round)
##Wd <- strptime(a$Date, format = "%m/%d/%y")
##WalshDate <- as.POSIXct(Wd,format="%m/%d/%y",tz=Sys.timezone())
loc <- a$Location
cv <- a$CV


cols <- c("Basin"= "#0072B2",
          "Intermediate"="#009E73",
          "Nearshore"= "yellow3")


CVLocation <- ggplot(data=a,aes(x=r,y=CV,fill=as.factor(loc))) +
  geom_boxplot()+
  scale_y_continuous(limits = c(0,3), breaks = seq(0,3,.5))+
  ##scale_x_datetime(breaks = as.POSIXct(as.Date(c("2020-06-14", ##"2020-06-28","2020-07-12","2020-07-26","2020-08-09","2020-08-23","2020-09-07","2020-09-20","2020-10-04","2020-1##0-18","2020-11-01","2020-11-12"))), labels =
##                     date_format("%m/%d"), 
##                   limits = c(as.POSIXct(as.Date("2020-06-07")), as.POSIXct(as.Date("2020-11-20"))))+
  scale_fill_manual(values = cols)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("Walsh") +
  labs(x = ("Date"), y=("Coefficient of Variation"), fill = ("Location"))+
  theme(plot.title = element_text(face = "bold",size = 12),
        axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=10,face="bold"),
        legend.position = "bottom")

CVLocation
```

### LilAp
```{r,message=F,warning=F}
rla <- b$Round
pla <- b$Parasite
locla <- b$Location
cvla <- b$CV



CVLocationLA <- ggplot(data=b,aes(x=as.factor(rla),y=cvla, fill=locla)) +
  geom_boxplot()+
  scale_y_continuous(limits = c(0,3), breaks = seq(0,3,.5))+
  ##scale_x_discrete(c("Nearshore","Intermediate","Basin"))+
  scale_fill_manual(values = cols)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("Little Appleton") +
  labs(x = ("Date"), y=("Coefficient of Variation"), fill = ("Location"))+
  theme(plot.title = element_text(face = "bold",size = 12)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=10,face="bold")) +
  theme(legend.position = "bottom")

CVLocationLA
```


### Cedar
```{r,message=F,warning=F}
rc <- c$Round
locc <- c$Locations
cvc <- c$CV

CVLocationC <- ggplot(data=c,aes(x=as.factor(rc),y=cvc, fill=locc)) +
  geom_boxplot()+
  ##geom_jitter(width = .1, height = 0, color="black", size=0.5, alpha=1) +
  scale_y_continuous(limits = c(0,3), breaks = seq(0,3,.5))+
  ##scale_x_discrete(c("Nearshore","Intermediate","Basin"))+
  scale_fill_manual(values = cols)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("Cedar") +
  labs(x = ("Date"), y=("Coefficient of Variation"), fill = ("Location"))+
  theme(plot.title = element_text(face = "bold",size = 12)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=10,face="bold")) +
  theme(legend.position = "bottom")

CVLocationC
```

### combo
```{r,message=F,warning=F}
combined = ggarrange(CVLocation,CVLocationLA,CVLocationC,
                     nrow = 3, ncol = 1,
                     common.legend = TRUE,
                     legend="bottom")

combined=annotate_figure(combined,top = text_grob("Patchiness", color = "black", face = "bold", size = 14))

combined


#### saving combined plot
ggsave(here("figures", "Combo_Plot_Patchiness_Location.pdf"), combined, width = 10, height = 10, dpi = 600)
```
