---
title: "SporeByDepthTimeCV"
author: "Elizabeth Davenport"
date: '2023-11-22'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial stuff, including loading packages and importing data

##loading packages
```{r,message=F,warning=F}
library(here)
library(rstatix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(ggpubr)
library(lubridate)
library(scales)
library(reshape2)
library(RColorBrewer)
library(ggsignif)
```
## loading files

```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/SporeByDepthTimeCV.Rmd")

# Load Files
a <- readr::read_csv(here("data/CV_Depth_All_Parasites.csv"))

```

```{r,message=F,warning=F}
col <- c("0"= "#C6DBEF", "1"= "#9ECAE1", "2"="#6BAED6", "3"="#4292C6","4"= "#2171B5","5"= "#08519C","6"= "#08306B")
col2 <-c("0"= "#F7FBFF", "1"= "#DEEBF7", "2"="#C6DBEF", "3"="#9ECAE1","4"= "#6BAED6","5"= "#4292C6","6"= "#2171B5", "7"="#084594")

o = a %>%
  filter(Parasite== "Ordospora")

lo<-o$Lake
cvo <- o$CV
do <- as.numeric(o$Depth)

df1<- data.frame(lo,do, cvo)

wtest<-compare_means(cvo ~ do,  data = df1, method="wilcox.test", paired = FALSE)

my_comparisons1<- list( c("0", "6"))
##significant difference 0 vs 6m


CVordo <- ggplot(data=df1,mapping=aes(y=do,x=cvo, fill = as.factor(do))) +
  geom_boxplot()+
  geom_jitter(width = 0, height = 0, color="black", size=0.5, alpha=1) +
  scale_y_reverse(limits = c(7.5, -0.5), breaks = seq(7,0,-1))+
  scale_x_continuous(limits = c(0,3.5), breaks = seq(0,3.5,0.5))+
  scale_fill_manual(values = col2)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle(expression(paste(bolditalic("O. pajunii")))) +
  labs(x = ("Coefficient of Variation"), y=("Depth (m)"))+
  theme(plot.title = element_text(face = "bold",size = 10)) +
  theme(axis.text=element_text(size=6, face = "bold"), 
        axis.title=element_text(size=8,face="bold")) +
  theme(legend.position = "none")


CVordo
```

```{r,message=F,warning=F}
b = a %>%
  filter(Parasite== "Blastulidium")

cvb <- b$CV
db <- b$Depth

df2<- data.frame(db, cvb)

wtest2<-compare_means(cvb ~ db,  data = df2, method="wilcox.test", paired = FALSE)
##no significant difference

CVbrood <- ggplot(data=b,aes(x=cvb,y=db, fill = as.factor(db))) +
  geom_boxplot()+  
  geom_jitter(width = 0, height = 0, color="black", size=0.5, alpha=1) +
  scale_y_reverse(limits = c(7.5, -0.5), breaks = seq(7,0,-1))+
  scale_x_continuous(limits = c(0,3.5), breaks = seq(0,3.5,0.5))+
  scale_fill_manual(values = col2)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle(expression(paste(bolditalic("B. paedophthorum")))) +
  labs(x = ("Coefficient of Variation"), y=("Depth (m)"))+
  theme(plot.title = element_text(face = "bold",size = 10)) +
  theme(axis.text=element_text(size=6, face = "bold"), 
        axis.title=element_text(size=8,face="bold")) +
  theme(legend.position = "none")

CVbrood
```

```{r,message=F,warning=F}

m = a %>%
  filter(Parasite== "Metschnikowia")

cvm <- m$CV
dm <- m$Depth

df3<- data.frame(dm, cvm)

wtest3<-compare_means(cvm ~ dm,  data = df3, method="wilcox.test", paired = FALSE)
##no significant difference

CVmetsch <- ggplot(data=m,aes(x=cvm,y=dm, fill = as.factor(dm))) +
  geom_boxplot()+
  geom_jitter(width = 0, height = 0, color="black", size=0.5, alpha=1) +
  scale_y_reverse(limits = c(7.5, -0.5), breaks = seq(7,0,-1))+
  scale_x_continuous(limits = c(0,3.5), breaks = seq(0,3.5,0.5))+
  scale_fill_manual(values = col2)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle(expression(paste(bolditalic("M. bicuspidata")))) +
  labs(x = ("Coefficient of Variation"), y=("Depth (m)"))+
  theme(plot.title = element_text(face = "bold",size = 10)) +
  theme(axis.text=element_text(size=6, face = "bold"), 
        axis.title=element_text(size=8,face="bold")) +
  theme(legend.position = "none")

CVmetsch
```

```{r,message=F,warning=F}

p = a %>%
  filter(Parasite== "Pasteuria")

cvp <- p$CV
dp <- p$Depth

df4<- data.frame(dp, cvp)

wtest4<-compare_means(cvp ~ dp,  data = df4, method="wilcox.test", paired = FALSE)
##no significant difference

CVpast <- ggplot(data=p,aes(x=cvp,y=dp, fill = as.factor(dp))) +
  geom_boxplot()+
  geom_jitter(width = 0, height = 0, color="black", size=0.5, alpha=1) +
  scale_y_reverse(limits = c(7.5, -0.5), breaks = seq(7,0,-1))+
  scale_x_continuous(limits = c(0,3.5), breaks = seq(0,3.5,0.5))+
  scale_fill_manual(values = col2)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle(expression(paste(bolditalic("P. ramosa")))) +
  labs(x = ("Coefficient of Variation"), y=("Depth (m)"))+
  theme(plot.title = element_text(face = "bold",size = 10)) +
  theme(axis.text=element_text(size=6, face = "bold"), 
        axis.title=element_text(size=8,face="bold")) +
  theme(legend.position = "none")

CVpast
```

```{r,message=F,warning=F}

s = a %>%
  filter(Parasite== "Spirobacillus")

cvs <- s$CV
ds <- s$Depth

df5<- data.frame(ds, cvs)

wtest5<-compare_means(cvs ~ ds,  data = df5, method="wilcox.test", paired = FALSE)
## significant difference 0 to 1,2,3

CVspiro <- ggplot(data=s,aes(x=cvs,y=ds, fill = as.factor(ds))) +
  geom_boxplot()+
  geom_jitter(width = 0, height = .0, color="black", size=0.5, alpha=1) +
  scale_y_reverse(limits = c(7.5, -0.5), breaks = seq(7,0,-1))+
  scale_x_continuous(limits = c(0,3.5), breaks = seq(0,3.5,0.5))+
  scale_fill_manual(values = col2)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle(expression(paste(bolditalic("S. cienkowskii")))) +
  labs(x = ("Coefficient of Variation"), y=("Depth (m)"))+
  theme(plot.title = element_text(face = "bold",size = 10)) +
  theme(axis.text=element_text(size=6, face = "bold"), 
        axis.title=element_text(size=8,face="bold")) +
  theme(legend.position = "none")

CVspiro
```

```{r,message=F,warning=F}
all.combined = ggarrange(CVmetsch,CVpast,CVbrood,
                         CVordo,CVspiro,
                         nrow = 3, ncol = 2)
all.combined=annotate_figure(all.combined,top = text_grob("Coefficient of Variation: Time", color = "black", face = "bold", size = 12))

all.combined

#### saving combined plot
ggsave(here("figures", "Combo_Plot_CV_By_Depth.jpg"), all.combined, width = 6, height = 9, dpi = 600)
```
