---
title: "SupportingInformationSporeViability"
author: "Elizabeth Davenport"
date: '2024-05-27'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial stuff, including loading packages and importing data

##loading packages
```{r,message=F,warning=F}
library(here)
library(rstatix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(ggpubr)
```
## loading files

```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/SupportingInformationSporeViability.Rmd")

# Load Files
a <- readr::read_csv(here("data/SupportingInformationSporeViability.csv"))

```


```{r,message=F,warning=F}
### defining factors and values
treatment <- as.factor(a$Treatment)
conc <- a$Concentration
sample <- a$SampleID
infection <- a$PercentInfection

##### Color scheme
col <- c("Control"="#009E73", "Frozen"="#0072B2", "UV"="#D55E00")


## creating a data frame
df1<- data.frame(sample,treatment,conc, infection)

#### setting comparisons for wilcox test
my_comparisons <- list( c("Control", "UV"),c("Control", "Frozen"),c("Frozen", "UV"))

## Wilcoxon Test
wtest<-compare_means(conc ~ treatment,  data = df1, method="wilcox.test", paired = FALSE)

sv.plot <- ggplot(data=df1) +
  geom_boxplot(aes(x=infection,y=conc, fill = as.factor(treatment)))+
  geom_point(aes(x=infection,y=conc))+
  scale_y_continuous(limits = c(-1, 8), breaks = seq(0,8,2))+
  scale_x_continuous(limits = c(-10,100), breaks = seq(0,100,10))+
  scale_fill_manual(values = col)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("Spore Viability") +
  labs(fill = "Treatment", x = ("Infection Prevalence"), y=("Concentration (copies/uL)"))+
  theme(plot.title = element_text(face = "bold",size = 12)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=10,face="bold")) +
  theme(legend.position = "bottom")

sv.plot

#### saving  plot
ggsave(here("figures", "SupportingInformationSporeViability.jpg"), sv.plot, width = 6, height = 6, dpi = 600)
```
