---
title: "WalshGravityCurrentFigure"
author: "Elizabeth Davenport"
date: '2023-11-22'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial stuff, including loading packages and importing data

##loading packages
```{r,message=F,warning=F}
library(here)
library(rstatix)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(lubridate)
library(scales)
library(ggpubr)
library(reshape2)
library(RColorBrewer)
```
## loading files

```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/WalshTemperatureProfileAndMixing.Rmd")

# Load Files
a <- readr::read_csv(here("data/SporeConcentrationsByDepthLocations.csv"))
b <- readr::read_csv(here("data/Walsh_Basin_Nearshore.csv"))
```

```{r,message=F,warning=F}
col <- c("0"= "#C6DBEF", "1"= "#9ECAE1", "2"="#6BAED6", "3"="#4292C6","4"= "#2171B5","5"= "#08519C","6"= "#08306B")
col2 <- c("Basin"="#0072B2", "Nearshore"="#009E73")
######### Walsh

wb = a %>%
  filter(Parasite== "Blastulidium",
         Lake=="Walsh",
         Location=="Basin"| Location=="Nearshore",
         Depth=="3")
locw<- wb$Location

concwb <- wb$ConcentrationLog10Plus1
pwb <- wb$Parasite
dwb <- wb$Depth
dwb <- as.factor(dwb)
yywb <- wb$Date
strptime(yywb, format = "%m/%d/%y")
lwb <- as.POSIXct(yywb,format="%m/%d/%y",tz=Sys.timezone())


walsh.brood <- ggplot(wb) +
  geom_point(aes(x=lwb,y=concwb, group=locw,color=locw), size=2) +
  geom_line(aes(x=lwb,y=concwb, group=locw, color=locw), size=1.5)+
  ##geom_smooth(aes(x=lwb,y=concwb, group=locw, color=locw),method = "loess", size = 1.5, span=.5, se=FALSE)+
  scale_colour_manual(values = col2)+
  scale_y_continuous(limits=c(0,6.5), breaks = seq(0,6.5,1))+
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), as.POSIXct(as.Date("2021-11-13"))))+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("B. paedophthorum") +
  theme(plot.title = element_text(face = "bold.italic",size = 14)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=12,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 12),
        legend.text=element_text(size=10,face="bold"),
        legend.position = "bottom") +  
  labs(colour = "Location", x = ("Date"), y = ("Log(Spore Concentration + 1)"))+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-09-22")), xmax=as.POSIXct(as.Date("2021-09-26")), ymin=0, ymax=Inf), alpha=.015, fill="grey90")+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-10-22")), xmax=as.POSIXct(as.Date("2021-10-28")), ymin=0, ymax=Inf), alpha = .015, fill="grey90")

######## Walsh MicG
wo = a %>%
  filter(Parasite== "Ordospora",
         Lake=="Walsh",
         Location=="Basin"| Location=="Nearshore",
         Depth=="3")
locwo<- wo$Location

concwo <- wo$ConcentrationLog10Plus1
pwo <- wo$Parasite
dwo <- wo$Depth
dwo <- as.factor(dwo)
yywo <- wo$Date
strptime(yywo, format = "%m/%d/%y")
lwo <- as.POSIXct(yywo,format="%m/%d/%y",tz=Sys.timezone())


walsh.micg <- ggplot(wo) +
  geom_point(aes(x=lwo,y=concwo, group=locwo,color=locwo), size=2) +
  geom_line(aes(x=lwo,y=concwo, group=locwo, color=locwo), size=1.5)+
  ##geom_smooth(aes(x=lwb,y=concwb, group=locw, color=locw),method = "loess", size = 1.5, span=.5, se=FALSE)+
  scale_colour_manual(values = col2)+
  scale_y_continuous(limits=c(0,6.5), breaks = seq(0,6.5,1))+
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), as.POSIXct(as.Date("2021-11-13"))))+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("O. pajunii") +
  theme(plot.title = element_text(face = "bold.italic",size = 14)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=12,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 12),
        legend.text=element_text(size=10,face="bold"),
        legend.position = "bottom") +  
  labs(colour = "Location", x = ("Date"), y = ("Log(Spore Concentration + 1)"))+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-09-22")), xmax=as.POSIXct(as.Date("2021-09-26")), ymin=0, ymax=Inf), alpha=.015, fill="grey90")+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-10-22")), xmax=as.POSIXct(as.Date("2021-10-28")), ymin=0, ymax=Inf), alpha = .015, fill="grey90")

######### Walsh Metsch
wm = a %>%
  filter(Parasite== "Metschnikowia",
         Lake=="Walsh",
         Location=="Basin"| Location=="Nearshore",
         Depth=="3")

locwm<-wm$Location

concwm <- wm$ConcentrationLog10Plus1
pwm <- wm$Parasite
dwm <- wm$Depth
dwm <- as.factor(dwm)
yywm <- wm$Date
strptime(yywm, format = "%m/%d/%y")
lwm <- as.POSIXct(yywm,format="%m/%d/%y",tz=Sys.timezone())

walsh.metsch <- ggplot(wm) +
  geom_point(aes(x=lwm,y=concwm, group=locwm,color=locwm), size=2) +
  geom_line(aes(x=lwm,y=concwm, group=locwm, color=locwm), size=1.5)+
  ##geom_smooth(aes(x=lwb,y=concwb, group=locw, color=locw),method = "loess", size = 1.5, span=.5, se=FALSE)+
  scale_colour_manual(values = col2)+
  scale_y_continuous(limits=c(0,6.5), breaks = seq(0,6.5,1))+
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), as.POSIXct(as.Date("2021-11-13"))))+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("M. bicuspidata") +
  theme(plot.title = element_text(face = "bold.italic",size = 14)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=12,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 12),
        legend.text=element_text(size=10,face="bold"),
        legend.position = "bottom") +  
  labs(colour = "Location", x = ("Date"), y = ("Log(Spore Concentration + 1)"))+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-09-22")), xmax=as.POSIXct(as.Date("2021-09-26")), ymin=0, ymax=Inf), alpha=.015, fill="grey90")+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-10-22")), xmax=as.POSIXct(as.Date("2021-10-28")), ymin=0, ymax=Inf), alpha = .015, fill="grey90")

####### Walsh Past

wp = a %>%
  filter(Parasite== "Pasteuria",
         Lake=="Walsh",
         Location=="Basin"| Location=="Nearshore",
         Depth=="3")

locwp<-wp$Location

concwp <- wp$ConcentrationLog10Plus1
pwp <- wp$Parasite
dwp <- wp$Depth
dwp <- as.factor(dwp)
yywp <- wp$Date
strptime(yywp, format = "%m/%d/%y")
lwp <- as.POSIXct(yywp,format="%m/%d/%y",tz=Sys.timezone())


walsh.past <- ggplot(wp) +
  geom_point(aes(x=lwp,y=concwp, group=locwp,color=locwp), size=2) +
  geom_line(aes(x=lwp,y=concwp, group=locwp, color=locwp), size=1.5)+
  ##geom_smooth(aes(x=lwb,y=concwb, group=locw, color=locw),method = "loess", size = 1.5, span=.5, se=FALSE)+
  scale_colour_manual(values = col2)+
  scale_y_continuous(limits=c(0,6.5), breaks = seq(0,6.5,1))+
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), as.POSIXct(as.Date("2021-11-13"))))+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("P. ramosa") +
  theme(plot.title = element_text(face = "bold.italic",size = 14)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=12,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 12),
        legend.text=element_text(size=10,face="bold"),
        legend.position = "bottom") +  
  labs(colour = "Location", x = ("Date"), y = ("Log(Spore Concentration + 1)"))+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-09-22")), xmax=as.POSIXct(as.Date("2021-09-26")), ymin=0, ymax=Inf), alpha=.015, fill="grey90")+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-10-22")), xmax=as.POSIXct(as.Date("2021-10-28")), ymin=0, ymax=Inf), alpha = .015, fill="grey90")

######## Walsh Spiro

ws = a %>%
  filter(Parasite== "Spirobacillus",
         Lake=="Walsh",
         Location=="Basin"| Location=="Nearshore",
         Depth=="3")

locws<-ws$Location

concws <- ws$ConcentrationLog10Plus1
pws <- ws$Parasite
dws <- ws$Depth
dws <- as.factor(dws)
yyws <- ws$Date
strptime(yyws, format = "%m/%d/%y")
lws <- as.POSIXct(yyws,format="%m/%d/%y",tz=Sys.timezone())


walsh.spiro <- ggplot(ws) +
  geom_point(aes(x=lws,y=concws, group=locws,color=locws), size=2) +
  geom_line(aes(x=lws,y=concws, group=locws, color=locws), size=1.5)+
  ##geom_smooth(aes(x=lwb,y=concwb, group=locw, color=locw),method = "loess", size = 1.5, span=.5, se=FALSE)+
  scale_colour_manual(values = col2)+
  scale_y_continuous(limits=c(0,6.5), breaks = seq(0,6.5,1))+
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), as.POSIXct(as.Date("2021-11-13"))))+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("S. cienkowskii") +
  theme(plot.title = element_text(face = "bold.italic",size = 14)) +
  theme(axis.text=element_text(size=10, face = "bold"), 
        axis.title=element_text(size=12,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 12),
        legend.text=element_text(size=10,face="bold"),
        legend.position = "bottom") +  
  labs(colour = "Location", x = ("Date"), y = ("Log(Spore Concentration + 1)"))+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-09-22")), xmax=as.POSIXct(as.Date("2021-09-26")), ymin=0, ymax=Inf), alpha=.015, fill="grey90")+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-10-22")), xmax=as.POSIXct(as.Date("2021-10-28")), ymin=0, ymax=Inf), alpha = .015, fill="grey90")

walsh.spiro

##########


z <- strptime(b$Date,format = "%m/%d/%y  %H:%M")
l <- as.POSIXct(z,format="%m/%d/%y %H:%M",tz=Sys.timezone())

W.TDiff.3 <- b$Diff.3

df.WTDiff3 <- data.frame(check.names = FALSE, time = l,
                         "3m" = W.TDiff.3)

df.WTDiff3 <- melt(df.WTDiff3,  id.vars = 'time', variable.name = 'series')

WTdiff3 = ggplot(df.WTDiff3, aes(time,value)) + 
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-10-22")), xmax=as.POSIXct(as.Date("2021-10-28")), ymin=-Inf, ymax=Inf), alpha = .015, fill="grey90")+
  geom_rect(aes(xmin=as.POSIXct(as.Date("2021-09-22")), xmax=as.POSIXct(as.Date("2021-09-26")), ymin=-Inf, ymax=Inf), alpha=.015, fill="grey90")+
  geom_line(aes(colour = series)) +
  scale_color_manual(values = "black") +
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black")) +
  scale_y_continuous(limits = c(-1.5, 1.5), breaks = seq(-1.5, 1.5, 0.5))+
  labs(x = "",
       y = (expression(bold("Temperature Difference " ( degree*C))))) +
  ggtitle("Thermal Difference: Basin - Nearshore") +
  theme(plot.title = element_text(face = "bold",size = 14)) +
  theme(axis.text=element_text(size=11, face = "bold"), 
        axis.title=element_text(size=14,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 14),
        legend.text=element_text(size=11,face="bold")) + 
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), 
                              as.POSIXct(as.Date("2021-11-13")))) +
  theme(legend.position = "none") +
  geom_hline(yintercept=0)


legw <- get_legend(walsh.brood)
walsh.combined = ggarrange(WTdiff3, walsh.brood, walsh.micg, walsh.metsch, 
                           walsh.past,walsh.spiro,
                           nrow = 3, ncol = 2, common.legend = TRUE,legend.grob = legw, legend="bottom")

walsh.combined=annotate_figure(walsh.combined,top = text_grob("Gravity Currents: Walsh 3m", color = "black", face = "bold", size = 16))

#### saving combined plot
ggsave(here("figures", "WalshCombinedSporesGravityCurrents3m_reordered.jpg"), walsh.combined, width = 10, height = 10, dpi = 300)
```